spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_lock?serverTimezone=UTC&characterEncoding=UTF-8
    username: emp
    password: 1234
  #    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;
#    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger : %msg%n"
#  level:
#    org.hibernate.SQL: debug
#    com.zaxxer.hikari: trace
#    com.zaxxer.hikari.HikariConfig: debug
#    org.springframework.orm.jpa: debug
#    org.springframework.transaction: debug